### ISSUE TITLE
Can not delete tag with number value

### ISSUE THREAD

**Issue by gcrescent** [one-signal/OneSignal-Android-SDK#13]
I have a tag that has number as it's value, and whenever I tried to delete the tag I got: 

java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
                                                               at com.onesignal.OneSignalStateSynchronizer.generateJsonDiff(OneSignalStateSynchronizer.java:94)
                                                               at com.onesignal.OneSignalStateSynchronizer.generateJsonDiff(OneSignalStateSynchronizer.java:82)
                                                               at com.onesignal.OneSignalStateSynchronizer.sendTags(OneSignalStateSynchronizer.java:472)
                                                               at com.onesignal.OneSignal.sendTags(OneSignal.java:644)
                                                               at com.onesignal.OneSignal.deleteTags(OneSignal.java:716)

This only happen in newest version because at tags deletion you change the value to empty String (OneSignal.java:716) but also try to cast it into Number (OneSignalStateSynchronizer.java:94).

**Comment by burtbenigni** [comment]
Same problem! 
Please fix it or nobody can delete any int type tag.

**Comment by illambo** [comment]
+1

**Comment by jkasten2** [comment]
Just fixed this in version 2.1.0.
