### ISSUE TITLE
onPause NPE

### ISSUE THREAD

**Issue by skywall** [one-signal/OneSignal-Android-SDK#3]
Hi, 

I'm trying to share some content with ACTION_SEND intents. Before share dialog (chooser) is shown application crashes with following exception:

java.lang.RuntimeException: Unable to pause activity {cz...../cz.....activity.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3086)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3041)
            at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3019)
            at android.app.ActivityThread.access$1000(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5179)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:614)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at com.onesignal.OneSignal.getGcmPreferences(OneSignal.java:760)
            at com.onesignal.OneSignal.GetUnsentActiveTime(OneSignal.java:744)
            at com.onesignal.OneSignal.onPaused(OneSignal.java:268)
            at cz.something.something.activity.MainActivity.onPause(MainActivity.java:77)
            at android.app.Activity.performPause(Activity.java:5350)
            at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1233)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3072)
            at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3041)
            at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3019)
            at android.app.ActivityThread.access$1000(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1216)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5179)
            at java.lang.reflect.Method.invokeNative(Native Method)

	@Override
	protected void onResume() {
		super.onResume();
		OneSignal.onResumed();
		App.bus().register(this);
	}

	@Override
	protected void onPause() {
		super.onPause();
		OneSignal.onPaused(); // < -- line 77
		App.bus().unregister(this);
	}

Sharing:
	Intent share = new Intent(Intent.ACTION_SEND);
	share.setType("image/jpeg");
	share.putExtra(Intent.EXTRA_STREAM, Uri.fromFile(imageFile));
	context.startActivity(Intent.createChooser(share, "Share"));

Thanks for every suggestion.

**Comment by jkasten2** [comment]
Hello,

Are you calling `OneSignal.init()` before OneSignal.onPaused(); gets called in your app? I believe this is creating the crash in your app. We will add a check for this order in our SDK in a future version so this does not crash.

Thanks.

**Comment by skywall** [comment]
Hi,

thanks for answer. You're right. OneSignal.init() hasn't been called. When user came back to application after "share action", other than "Launcher" activity has been started.

Thanks.

**Comment by jkasten2** [comment]
Fixed, no longer crashes even if init is not called or is called out of order.

commit d053c5ff54d17031af356e104779118070a84d85
version 1.9.0
