### ISSUE TITLE
UNEXPECTED TOP-LEVEL EXCEPTION

### ISSUE THREAD

**Issue by francocorreasosa** [one-signal/OneSignal-Android-SDK#39]
I got this error after linking the library with the Android project (React Native)
```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dex.DexException: Multiple dex files define Lcom/google/android/gms/internal/zzas;
Unknown source file : 	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
Unknown source file : 	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
Unknown source file : 	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
Unknown source file : 	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
Unknown source file : 	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:502)
Unknown source file : 	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:334)
Unknown source file : 	at com.android.dx.command.dexer.Main.run(Main.java:277)
Unknown source file : 	at com.android.dx.command.dexer.Main.main(Main.java:245)
Unknown source file : 	at com.android.dx.command.Main.main(Main.java:106)
```

**Comment by jkasten2** [comment]
This means there is 2 copies of the Google Play services library. You need to remove one.

**Comment by francocorreasosa** [comment]
mmm. how can I do that? I don't know almost anything of Android dev. The repo is [francocorreasosa/inumet-react-native](https://github.com/francocorreasosa/inumet-react-native)

**Comment by jkasten2** [comment]
Moving the discussion to their repo.

**Comment by francocorreasosa** [comment]
But that happened after I added THIS library to the app... Now I see why OneSignal is free...
