### ISSUE TITLE
Android - POST Error thrown from network stack.

### ISSUE THREAD

**Issue by harshitaahuja** [one-signal/OneSignal-Android-SDK#51]
We are facing multiple errors while integrating onesignal in android.
**First error -** 
`W/OneSignal: POST Error thrown from network stack. 
                                                               javax.net.ssl.SSLException: Read error: ssl=0xafcab200: I/O error during system call, Connection reset by peer
                                                                   at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
                                                                   at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:699)
                                                                   at com.android.okio.Okio$2.read(Okio.java:113)
                                                                   at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:147)
                                                                   at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:94)
                                                                   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
                                                                   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                                                                   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
                                                                   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
                                                                   at com.onesignal.OneSignalRestClient.makeRequest(OneSignalRestClient.java:109)
                                                                   at com.onesignal.OneSignalRestClient.postSync(OneSignalRestClient.java:77)
                                                                   at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:515)
                                                                   at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:440)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
05-14 13:44:42.262 16816-16865/com.cognistx.monro W/OneSignal: Failed last request. statusCode: -1
                                                               response: null`

**Second error -** 
`W/OneSignal: POST Error thrown from network stack. 
                                                               java.io.EOFException
                                                                   at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:95)
                                                                   at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:179)
                                                                   at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
                                                                   at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:628)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:388)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
                                                                   at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
                                                                   at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
                                                                   at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
                                                                   at com.onesignal.OneSignalRestClient.makeRequest(OneSignalRestClient.java:109)
                                                                   at com.onesignal.OneSignalRestClient.postSync(OneSignalRestClient.java:77)
                                                                   at com.onesignal.OneSignalStateSynchronizer.syncUserState(OneSignalStateSynchronizer.java:515)
                                                                   at com.onesignal.OneSignalStateSynchronizer$NetworkHandlerThread$1.run(OneSignalStateSynchronizer.java:440)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
05-14 13:45:12.579 16816-16865/com.cognistx.monro W/OneSignal: Failed last request. statusCode: -1
                                                               response: null`

This is very critical for us.
Need help ASAP.

**Comment by gaganutreja** [comment]
Facing same issue :(

**Comment by jkasten2** [comment]
@harshitaahuja @gaganutreja How often does this this error occur? Can you make sure the device's internet connection is stable as the `Connection reset by peer at` normally happens when the network isn't stable. Can you try other Android devices and network connections?

Our SDK does automatically retry so nothing is lost during connection issues. See the following posts for information on connection error you're seeing.
http://stackoverflow.com/questions/35463477/ioexception-javax-net-ssl-sslhandshakeexception-ssl-handshake-aborted-ssl-0x
http://stackoverflow.com/a/31345743/1244574

Thanks.

**Comment by jkasten2** [comment]
@harshitaahuja @gaganutreja Were you able to try the suggestions above? Still seeing an issue?

**Comment by jkasten2** [comment]
Feel free to reopen this issue if it is still happening to you.

**Comment by imaginashaun** [comment]
This is still an issue

**Comment by redoc123** [comment]
This is still and issue. I have same issues when trying from ionic2. following are the details of the ionic app installation. 

**ionic info** 

Cordova CLI: 7.0.1 
Ionic Framework Version: 3.5.0
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.12
ios-deploy version: 1.8.6 
ios-sim version: 5.0.8 
OS: macOS Sierra
Node Version: v7.5.0
Xcode version: Xcode 8.3.3 Build version 8E3004b

**ionic plugin info**
cordova-plugin-console 1.0.5 "Console"
cordova-plugin-device 1.1.4 "Device"
cordova-plugin-splashscreen 4.0.3 "Splashscreen"
cordova-plugin-statusbar 2.2.2 "StatusBar"
cordova-plugin-whitelist 1.3.1 "Whitelist"
ionic-plugin-keyboard 2.2.1 "Keyboard"
onesignal-cordova-plugin 2.1.2 "OneSignal Push Notifications"

**Comment by HebaMohamed** [comment]
I still got similar issue too with OneSignal:3.11.4
`W/OneSignal: OneSignalRestClient: null Error thrown from network stack. `
and still unable to find active device player id on the dashboard

There is any update to solve that please?

**Comment by SourcCode-eg** [comment]
> I still got similar issue too with OneSignal:3.11.4
> `W/OneSignal: OneSignalRestClient: null Error thrown from network stack. `
> and still unable to find active device player id on the dashboard
> 
> There is any update to solve that please?

do you have any solution

**Comment by tamdinh** [comment]
I have the same issue. Any update?

**Comment by Lawati97** [comment]
I am facing the same issue and was wondering if anyone was able to solve it?
