### ISSUE TITLE
NotificationExtenderService - NumberFormatException

### ISSUE THREAD

**Issue by jkasten2** [one-signal/OneSignal-Android-SDK#56]
`Error assigning OSNotificationPayload values!` is being logged from `NotificationExtenderService` when it is turned on.

````
Error assigning OSNotificationPayload values!
java.lang.NumberFormatException: Invalid int: "null"
    at java.lang.Integer.invalidInt(Integer.java:137)
    at java.lang.Integer.parseInt(Integer.java:354)
    at java.lang.Integer.parseInt(Integer.java:331)
    at com.onesignal.NotificationExtenderService.processIntent(NotificationExtenderService.java:122)
    at com.onesignal.NotificationExtenderService.onHandleIntent(NotificationExtenderService.java:95)
    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:136)
    at android.os.HandlerThread.run(HandlerThread.java:61)
````

This is preventing some properties like `additionalData` from being assigned when `onNotificationProcessing` is called.

Work around.
Set `android_visibility` to 1 or 0 from the [create notification](http://documentation.onesignal.com/v2.0/docs/notifications-create-notification) REST API POST call

**Comment by jkasten2** [comment]
Fixed in version 2.4.1
https://github.com/one-signal/OneSignal-Android-SDK/releases/tag/2.4.1
